# Foundry Configuration File
# Default definitions: https://github.com/gakonst/foundry/blob/b7917fa8491aedda4dd6db53fbb206ea233cd531/config/src/lib.rs#L782
# See more config options at: https://github.com/gakonst/foundry/tree/master/config

# The Default Profile
[profile.default]
# Sets the concrete solc version to use
# This overrides the `auto_detect_solc` value
solc_version = '0.8.15'
# auto_detect_solc = true
src = 'src'
out = 'out'
libs = ["node_modules", "lib", "src"]
gas_reports = ["*"]
# Increase optimizer_runs
optimizer = true
optimizer_runs = 1_000
# Fuzz more than the default 256
fuzz_runs = 1_000
# Configure remappings

remappings = [
  "@utils/=src/v1/utils",
  "@std=lib/forge-std/src/",
  "@helpers/=src/v1/helpers/",
  "@libraries/=src/v1/libraries/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]
