/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type {
  PriceFeedConsumer,
  PriceFeedConsumerInterface,
} from "../PriceFeedConsumer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_priceFeed",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "getLatestPrice",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPriceFeed",
    outputs: [
      {
        internalType: "contract AggregatorV3Interface",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b5060405161025238038061025283398101604081905261002f91610040565b6001600160a01b0316608052610070565b60006020828403121561005257600080fd5b81516001600160a01b038116811461006957600080fd5b9392505050565b6080516101c26100906000396000818160630152609201526101c26000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80638e15f4731461003b5780639e87a5cd14610056575b600080fd5b61004361008d565b6040519081526020015b60405180910390f35b6040516001600160a01b037f000000000000000000000000000000000000000000000000000000000000000016815260200161004d565b6000807f00000000000000000000000000000000000000000000000000000000000000006001600160a01b031663feaf968c6040518163ffffffff1660e01b815260040160a060405180830381865afa1580156100ee573d6000803e3d6000fd5b505050506040513d601f19601f82011682018060405250810190610112919061013c565b509195945050505050565b805169ffffffffffffffffffff8116811461013757600080fd5b919050565b600080600080600060a0868803121561015457600080fd5b61015d8661011d565b94506020860151935060408601519250606086015191506101806080870161011d565b9050929550929590935056fea26469706673582212205d56a748554f8907ca9d26d6d4d017e28b87fdd562431b89a7b70e60934e1a2b64736f6c634300080f0033";

type PriceFeedConsumerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PriceFeedConsumerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PriceFeedConsumer__factory extends ContractFactory {
  constructor(...args: PriceFeedConsumerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _priceFeed: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<PriceFeedConsumer> {
    return super.deploy(
      _priceFeed,
      overrides || {}
    ) as Promise<PriceFeedConsumer>;
  }
  override getDeployTransaction(
    _priceFeed: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_priceFeed, overrides || {});
  }
  override attach(address: string): PriceFeedConsumer {
    return super.attach(address) as PriceFeedConsumer;
  }
  override connect(signer: Signer): PriceFeedConsumer__factory {
    return super.connect(signer) as PriceFeedConsumer__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PriceFeedConsumerInterface {
    return new utils.Interface(_abi) as PriceFeedConsumerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PriceFeedConsumer {
    return new Contract(address, _abi, signerOrProvider) as PriceFeedConsumer;
  }
}
