/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  PublicGoodsAreGood,
  PublicGoodsAreGoodInterface,
} from "../PublicGoodsAreGood";

const _abi = [
  {
    inputs: [],
    name: "ENS_RESOVLER_ADDRESS",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "OP_RETROACTIVE_GOODS_FUNDS",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PROTOCOL_GUILD_NODE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ens",
    outputs: [
      {
        internalType: "contract ENS",
        name: "",
        type: "ENS",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class PublicGoodsAreGood__factory {
  static readonly abi = _abi;
  static createInterface(): PublicGoodsAreGoodInterface {
    return new utils.Interface(_abi) as PublicGoodsAreGoodInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PublicGoodsAreGood {
    return new Contract(address, _abi, signerOrProvider) as PublicGoodsAreGood;
  }
}
