/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type {
  PublicGoodsAreGood,
  PublicGoodsAreGoodInterface,
} from "../PublicGoodsAreGood";

const _abi = [
  {
    inputs: [],
    name: "ENS_RESOVLER_ADDRESS",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "OP_RETROACTIVE_GOODS_ADRESS",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "OP_RETROACTIVE_GOODS_ENS",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PROTOCOL_GUILD_ADRESS",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PROTOCOL_GUILD_ENS",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ens",
    outputs: [
      {
        internalType: "contract ENS",
        name: "",
        type: "ENS",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x61015561003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361061006c5760003560e01c8063251d0eba146100715780633f15457f146100715780638784323d146100a4578063d3ae622c146100ce578063e2a30840146100e9578063e83d59fe14610104575b600080fd5b6100876e0c2e074ec69a0dfb2997ba6c7d2e1e81565b6040516001600160a01b0390911681526020015b60405180910390f35b6100c07109ea05ae4cae8e4de5acededec8e65ccae8d60731b81565b60405190815260200161009b565b6100c0700e0e4dee8dec6ded8ceead2d8c85ccae8d607b1b81565b610087731230f3c6b9cdf2f4b7d406ebc010e71dfb20eef481565b610087739876644568157cc35c0ad942b4ca2de2124b37328156fea26469706673582212202fd48bd86268c3ed901427b8031c266c7a6dd3ebc272521f40dea560a8cdd42564736f6c634300080f0033";

type PublicGoodsAreGoodConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PublicGoodsAreGoodConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PublicGoodsAreGood__factory extends ContractFactory {
  constructor(...args: PublicGoodsAreGoodConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<PublicGoodsAreGood> {
    return super.deploy(overrides || {}) as Promise<PublicGoodsAreGood>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): PublicGoodsAreGood {
    return super.attach(address) as PublicGoodsAreGood;
  }
  override connect(signer: Signer): PublicGoodsAreGood__factory {
    return super.connect(signer) as PublicGoodsAreGood__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PublicGoodsAreGoodInterface {
    return new utils.Interface(_abi) as PublicGoodsAreGoodInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PublicGoodsAreGood {
    return new Contract(address, _abi, signerOrProvider) as PublicGoodsAreGood;
  }
}
