/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface PublicGoodsAreGoodInterface extends utils.Interface {
  functions: {
    "ENS_RESOVLER_ADDRESS()": FunctionFragment;
    "OP_RETROACTIVE_GOODS_FUNDS()": FunctionFragment;
    "PROTOCOL_GUILD_NODE()": FunctionFragment;
    "ens()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "ENS_RESOVLER_ADDRESS"
      | "OP_RETROACTIVE_GOODS_FUNDS"
      | "PROTOCOL_GUILD_NODE"
      | "ens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ENS_RESOVLER_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OP_RETROACTIVE_GOODS_FUNDS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_GUILD_NODE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ens", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "ENS_RESOVLER_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OP_RETROACTIVE_GOODS_FUNDS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_GUILD_NODE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ens", data: BytesLike): Result;

  events: {};
}

export interface PublicGoodsAreGood extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PublicGoodsAreGoodInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ENS_RESOVLER_ADDRESS(overrides?: CallOverrides): Promise<[string]>;

    OP_RETROACTIVE_GOODS_FUNDS(overrides?: CallOverrides): Promise<[string]>;

    PROTOCOL_GUILD_NODE(overrides?: CallOverrides): Promise<[string]>;

    ens(overrides?: CallOverrides): Promise<[string]>;
  };

  ENS_RESOVLER_ADDRESS(overrides?: CallOverrides): Promise<string>;

  OP_RETROACTIVE_GOODS_FUNDS(overrides?: CallOverrides): Promise<string>;

  PROTOCOL_GUILD_NODE(overrides?: CallOverrides): Promise<string>;

  ens(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    ENS_RESOVLER_ADDRESS(overrides?: CallOverrides): Promise<string>;

    OP_RETROACTIVE_GOODS_FUNDS(overrides?: CallOverrides): Promise<string>;

    PROTOCOL_GUILD_NODE(overrides?: CallOverrides): Promise<string>;

    ens(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    ENS_RESOVLER_ADDRESS(overrides?: CallOverrides): Promise<BigNumber>;

    OP_RETROACTIVE_GOODS_FUNDS(overrides?: CallOverrides): Promise<BigNumber>;

    PROTOCOL_GUILD_NODE(overrides?: CallOverrides): Promise<BigNumber>;

    ens(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ENS_RESOVLER_ADDRESS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    OP_RETROACTIVE_GOODS_FUNDS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    PROTOCOL_GUILD_NODE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ens(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
