export { default as PublicGoodsAreGoodAbi } from "../abis/PublicGoodsAreGood.json"
// export { default as EIP712AcknowledgementAbi } from "../abis/EIP712Acknowledgement.json"
// export { default as EIP712RegistrationAbi } from "../abis/EIP712Registration.json"
// export { default as SourceRegistryAbi } from "../abis/SourceRegistry.json"
// export { default as TargetRegistryAbi } from "../abis/TargetRegistry.json"
export { default as StolenWalletNFTAbi } from "../abis/StolenWalletNFT.json"
export { default as StolenWalletRegistryAbi } from "../abis/StolenWalletRegistry.json"

export { PriceFeedConsumer__factory as PriceFeedConsumerFactory } from "../typechain/factories/PriceFeedConsumer__factory"
export { PublicGoodsAreGood__factory as PublicGoodsAreGoodFactory } from "../typechain/factories/PublicGoodsAreGood__factory"
// export { TargetRegistry__factory as TargetRegistryFactory } from "../typechain/factories/TargetRegistry__factory"
// export { SourceRegistry__factory as SourceRegistryFactory } from "../typechain/factories/SourceRegistry__factory"
export { StolenWalletNFT__factory as StolenWalletNFTFactory } from "../typechain/factories/StolenWalletNFT__factory"
export { StolenWalletRegistry__factory as StolenWalletRegistryFactory } from "../typechain/factories/StolenWalletRegistry__factory"
